class Resume {
  final String fullName;
  final String jobTitle;
  final String experienceLevel;
  final List<String> skills;
  final List<Education> education;
  final List<WorkExperience> experience;
  final String summary; // Generated by AI
  final String email;
  final String phone;
  final String linkedin;
  final String? address;
  final List<String> languages;
  final List<String> interests;
  final String selectedTemplateId;

  Resume({
    required this.fullName,
    required this.jobTitle,
    required this.experienceLevel,
    required this.skills,
    required this.education,
    required this.experience,
    required this.summary,
    required this.email,
    required this.phone,
    required this.linkedin,
    this.address,
    this.languages = const [],
    this.interests = const [],
    this.selectedTemplateId = 'modern',
  });

  Resume copyWith({
    String? fullName,
    String? jobTitle,
    String? experienceLevel,
    List<String>? skills,
    List<Education>? education,
    List<WorkExperience>? experience,
    String? summary,
    String? email,
    String? phone,
    String? linkedin,
    String? address,
    List<String>? languages,
    List<String>? interests,
    String? selectedTemplateId,
  }) {
    return Resume(
      fullName: fullName ?? this.fullName,
      jobTitle: jobTitle ?? this.jobTitle,
      experienceLevel: experienceLevel ?? this.experienceLevel,
      skills: skills ?? this.skills,
      education: education ?? this.education,
      experience: experience ?? this.experience,
      summary: summary ?? this.summary,
      email: email ?? this.email,
      phone: phone ?? this.phone,
      linkedin: linkedin ?? this.linkedin,
      address: address ?? this.address,
      languages: languages ?? this.languages,
      interests: interests ?? this.interests,
      selectedTemplateId: selectedTemplateId ?? this.selectedTemplateId,
    );
  }
}

class Education {
  final String school;
  final String degree;
  final String year;

  Education({required this.school, required this.degree, required this.year});
}

class WorkExperience {
  final String company;
  final String role;
  final String duration;
  final String description; // Generated by AI

  WorkExperience({
    required this.company,
    required this.role,
    required this.duration,
    required this.description,
  });
}
